/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "SiteBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SiteLogForwarder": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SiteLogGroup": {
      "siteLogGroupName": string
      "type": "sst.sst.Linkable"
    }
    "SiteLogsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SiteRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
  }
}
