name: release-dev

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

env:
  TARGET_ACCOUNT_ID: ${{ secrets.DEV_ACCOUNT_ID }}
  CHANGE_SET_NAME: release-${{ github.run_number }}-${{ github.run_attempt }}
  CHANGE_SET_DESCRIPTION: ${{ github.event.head_commit.message }}
  ENVIRONMENT_NAME: dev

permissions:
  id-token: write
  contents: write
  packages: read

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.barney.dev
    steps:
      - uses: actions/checkout@v4
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ env.TARGET_ACCOUNT_ID }}:role/github-actions
          role-session-name: GitHubActions-${{ github.run_id }}
      - name: Deploy
        run: |
          npm ci
          npm run types
          npm run infra:barneydev:deploy
